CREATE TABLE Book(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(200) NOT NULL UNIQUE,
    author varchar(100) NOT NULL,
    date_of_creation int NOT NULL,
    person_id int REFERENCES Person(id) ON DELETE SET NULL
    taken_at DATE
);
