CREATE TABLE Book(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(200) NOT NULL UNIQUE,
    author varchar(100) NOT NULL,
    date_of_creation int NOT NULL,
    person_id int REFERENCES Person(id) ON DELETE SET NULL
    taken_at DATE
);

INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('City of Heroes', 'Michael Burns', 1920, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Our secret', 'Lorena Conley', 1989, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Kindred spirits', 'Stephen Cunningham', 1876, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Empty eyes', 'Lauren Marsh', 1913, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Sea battle', 'Clinton Small', 1991, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Space invaders', 'John Doe', 1985, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Super Mario Bros', 'Shigeru Miyamoto', 1985, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Tetris', 'Alexey Pajitnov', 1984, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Legend of Zelda', 'Shigeru Miyamoto', 1986, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Mortal Kombat', 'Ed Boon and John Tobias', 1992, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Lost City', 'Jessica Lee', 2008, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Chosen One', 'Erica James', 2012, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Great Escape', 'Anthony Smith', 1999, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Frozen in Time', 'Olivia Blake', 2016, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Last Resort', 'Simon Green', 2005, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Forbidden Forest', 'Lena Martin', 2014, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Secret Society', 'Max Bennett', 2001, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Island of Secrets', 'Sophie Coleman', 2018, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Final Hour', 'Alex Walker', 2009, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Hidden Truth', 'Ella Rose', 2015, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Стражи Потустороннего', 'Артемий Иванов', 2018, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Lost Tower', 'Olivia Green', 2005, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Охотник за тенями', 'Максим Ковалев', 2019, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Enchanted Forest', 'Sophia Stone', 2012, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Тайная история', 'Елена Петрова', 2008, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Hidden Power', 'Lucas Martin', 2016, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Последний охотник', 'Анна Сидорова', 2017, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Forbidden Kingdom', 'Emily Reed', 2010, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Таинственный лабиринт', 'Дмитрий Новиков', 2014, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Secret Place', 'Daniel Thompson', 2003, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Забытое прошлое', 'Алиса Крылова', 2009, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Mysterious Case', 'Oliver Adams', 2011, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Путь в неизведанное', 'Евгений Белов', 2013, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Curse of Shadows', 'Hannah Wilson', 2007, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Тайный удар', 'Максим Соловьев', 2019, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Forgotten Prophecy', 'Ethan Scott', 2015, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Скрытые силы', 'Анна Иванова', 2018, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Vanishing City', 'Olivia Walker', 2006, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Затерянный остров', 'Даниил Козлов', 2017, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Secret Code', 'Gabriel Evans', 2014, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Таинственные легенды', 'Александра Николаева', 2016, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Hidden Artifact', 'Natalie Roberts', 2004, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Загадочное наследие', 'Иван Фёдоров', 2010, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Forbidden Scroll', 'Sophie Turner', 2013, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Секреты прошлого', 'Артём Смирнов', 2012, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Lost Treasure', 'Owen Harris', 2008, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Запретный мир', 'Ксения Зайцева', 2017, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Hidden Passage', 'Emily Foster', 2009, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Загадка прошлого', 'Александр Ковалёв', 2015, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Enigmatic Puzzle', 'Charles Peterson', 2007, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Тайна тёмных сил', 'Ирина Морозова', 2018, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Forgotten Diary', 'Mia Thompson', 2011, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Проклятая реальность', 'Михаил Козлов', 2014, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Hidden Key', 'Benjamin Cooper', 2006, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('Тайные тайны', 'Екатерина Андреева', 2019, null);
INSERT INTO Book(name, author, date_of_creation, person_id) VALUES ('The Mystery House', 'Lily Smith', 2003, null);
